
const FAQ = () => {
    const faqList = [
        {
            question: "What is Chromakopia Font Generator?",
            answer: "Chromakopia Font Generator is a free online tool that helps you create beautiful text images. Simply type your text into Chromakopia, customize the style, colors, and background, and get a shareable image instantly. Chromakopia is perfect for creating social media posts, profile pictures, and creative visual content."
        },
        {
            question: "How to use Chromakopia Font Generator?",
            answer: "Using Chromakopia Font Generator is simple: 1. Type your text into Chromakopia's input box 2. Use Chromakopia's style options to customize your text color and style 3. Choose a background color or upload your own image to Chromakopia 4. Preview your design in real-time 5. Download your Chromakopia creation or share it directly to social media. No design skills needed!"
        },
        {
            question: "What customization options are available in Chromakopia?",
            answer: "Chromakopia Font Generator offers multiple customization options: text color, font style, background color, and custom background image upload. Every change you make in Chromakopia is previewed in real-time, allowing you to perfect your design. Chromakopia's intuitive interface makes it easy to create exactly what you envision."
        },
        {
            question: "Can I download the images I create with Chromakopia?",
            answer: "Yes! All images you create with Chromakopia can be downloaded instantly in high quality. Simply click the download button in Chromakopia once you're happy with your design. Images created with Chromakopia Font Generator are perfect for social media, digital platforms, or personal use."
        },
        {
            question: "How can I share my Chromakopia creations?",
            answer: "You can share your Chromakopia creations directly from our platform to social media, or download and share them manually. Each image made with Chromakopia comes with easy sharing options. Chromakopia Font Generator makes it simple to post your creations anywhere you want."
        },
        {
            question: "Is Chromakopia Font Generator free to use?",
            answer: "Yes, Chromakopia Font Generator is completely free to use. All of Chromakopia's features including text customization, background options, downloading, and sharing are available to everyone at no cost. You can use Chromakopia as much as you want without any charges."
        },
        {
            question: "Can I use my own background image in Chromakopia?",
            answer: "Yes! Chromakopia Font Generator allows you to upload your own background image to create truly unique designs. Chromakopia supports common image formats like JPG and PNG. Just make sure you have the rights to use any images you upload to Chromakopia."
        },
        {
            question: "What image format will I receive from Chromakopia?",
            answer: "Your Chromakopia creations are downloaded in high-quality PNG format, ensuring clarity and maintaining transparency where applicable. Images generated by Chromakopia Font Generator are optimized for social media and digital use while maintaining professional quality."
        },
        {
            question: "Does Chromakopia Font Generator work on mobile devices?",
            answer: "Yes, Chromakopia Font Generator is fully mobile-responsive. You can create, customize, download, and share Chromakopia images directly from your smartphone or tablet. Chromakopia's interface adapts to your screen size for the best experience."
        },
        {
            question: "Are there any size limits for images in Chromakopia?",
            answer: "The images generated by Chromakopia are optimized for social media use while maintaining high quality. For custom background uploads to Chromakopia Font Generator, we recommend using images under 5MB for the best performance. Chromakopia ensures your final images look great regardless of size."
        }
    ];

    return (
        <>
            <h2 className="text-2xl font-bold text-gray-800 text-center mb-8">
                Chromakopia Font Generator FAQ
            </h2>
            <div className="md:grid md:grid-cols-2 md:gap-6 space-y-4 md:space-y-0">
                {faqList.map((faq, index) => (
                    <div
                        key={index}
                        className="bg-white rounded-md shadow p-6 hover:shadow-md transition-shadow"
                    >
                        <h3 className="font-semibold text-gray-800 mb-3">
                            {faq.question}
                        </h3>
                        <div className="text-gray-600 leading-relaxed">
                            {faq.answer}
                        </div>
                    </div>
                ))}
            </div>
        </>
    )
};

export default FAQ;